version: 2

project_name: poke-cli

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.version=v1.3.3

archives:
  - formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
      - formats: [ 'zip' ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: poke-cli
    conflicts:
      - formula: poke-cli
    repository:
      owner: digitalghost-dev
      name: homebrew-tap
      token: "{{.Env.GITHUB_TOKEN}}"
    homepage: "https://github.com/digitalghost-dev/poke-cli"
    description: "A hybrid CLI/TUI tool written in Go for viewing Pokémon data from the terminal!"
    license: "Apache License 2.0"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poke-cli"]
          end