name: Lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - 'card_data/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.1
          skip-cache: true
